channels:
  - rapidsai
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - plotly=4.5
  - cudf=0.15
  - dask-cuda
  - datashader>=0.11.1
  - dash=1.8
  - dash-bootstrap-components
  - cudatoolkit=10.2  
  - dash-daq=0.3.2
  - gunicorn=20.0
  - pyproj
  - requests